#!/usr/bin/env python3
"""
generate_barrels.py
---------------------------------------------------
Auto-generates an index.js barrel file in EVERY folder,
re-exporting the named exports found in each .js file
in that folder (skips node_modules, dist, .git, index.js).

Usage:
    python3 generate_barrels.py ./src
    python3 generate_barrels.py ./src --dry     (preview only, no write)

Detects:
    export const X = ...
    export function X(...)
    export class X ...
    export { A, B as C }
Skips "export default" (no stable name to re-export cleanly).
"""

import os
import re
import sys

IGNORE_DIRS = {"node_modules", "dist", "build", ".git", "coverage"}

EXPORT_PATTERNS = [
    re.compile(r"export\s+const\s+([A-Za-z_$][\w$]*)"),
    re.compile(r"export\s+function\s*\*?\s*([A-Za-z_$][\w$]*)"),
    re.compile(r"export\s+class\s+([A-Za-z_$][\w$]*)"),
    re.compile(r"export\s+let\s+([A-Za-z_$][\w$]*)"),
]

EXPORT_BRACE_PATTERN = re.compile(r"export\s*\{([^}]+)\}")
AS_PATTERN = re.compile(r"^([A-Za-z_$][\w$]*)\s+as\s+([A-Za-z_$][\w$]*)$")
BARE_NAME_PATTERN = re.compile(r"^[A-Za-z_$][\w$]*$")


def get_export_names(content: str) -> list:
    names = set()

    for pattern in EXPORT_PATTERNS:
        for m in pattern.finditer(content):
            names.add(m.group(1))

    for brace_match in EXPORT_BRACE_PATTERN.finditer(content):
        inner = brace_match.group(1)
        for part in inner.split(","):
            piece = part.strip()
            if not piece:
                continue
            as_match = AS_PATTERN.match(piece)
            if as_match:
                names.add(as_match.group(2))
            elif BARE_NAME_PATTERN.match(piece):
                names.add(piece)

    return sorted(names)


def process_folder(dir_path: str, dry_run: bool, out_name: str = "index.js") -> None:
    try:
        entries = sorted(os.listdir(dir_path))
    except OSError as e:
        print(f"Skipping {dir_path}: {e}")
        return

    # Pass 1: collect exports per file
    file_exports = []  # list of (entry_name, [names])
    for entry in entries:
        full_path = os.path.join(dir_path, entry)

        if os.path.isdir(full_path):
            if entry in IGNORE_DIRS:
                continue
            process_folder(full_path, dry_run, out_name)  # recurse first
            continue

        if not entry.endswith(".js"):
            continue
        if entry == out_name:
            continue

        with open(full_path, "r", encoding="utf-8") as f:
            content = f.read()

        names = get_export_names(content)
        if names:
            file_exports.append((entry, names))

    if not file_exports:
        return

    # Pass 2: detect name collisions across files in this folder
    owner = {}       # name -> first file that claimed it
    conflicts = {}   # name -> list of files fighting over it
    for entry, names in file_exports:
        for name in names:
            if name in owner:
                conflicts.setdefault(name, [owner[name]])
                conflicts[name].append(entry)
            else:
                owner[name] = entry

    if conflicts:
        print(f"\n⚠ CONFLICTS in {dir_path}:")
        for name, files in conflicts.items():
            print(f"    '{name}' exported by: {', '.join(files)} -- skipped, fix manually")

    lines = []
    for entry, names in file_exports:
        keep = [n for n in names if n not in conflicts]
        if not keep:
            continue
        import_name = "./" + entry
        lines.append(f"export {{ {', '.join(keep)} }} from '{import_name}';")

    if not lines:
        return

    lines.sort()
    header = f"// AUTO-GENERATED by generate_barrels.py -- do not edit by hand\n\n"
    output = header + "\n".join(lines) + "\n"
    index_path = os.path.join(dir_path, out_name)

    if dry_run:
        print(f"\n--- {index_path} ---")
        print(output)
    else:
        with open(index_path, "w", encoding="utf-8") as f:
            f.write(output)
        print(f"✔ wrote {index_path} ({len(lines)} file(s) re-exported)")


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 generate_barrels.py <rootDir> [--dry] [--name barrel.js]")
        sys.exit(1)

    root_arg = sys.argv[1]
    dry_run = "--dry" in sys.argv

    out_name = "index.js"
    if "--name" in sys.argv:
        idx = sys.argv.index("--name")
        if idx + 1 < len(sys.argv):
            out_name = sys.argv[idx + 1]
        else:
            print("Missing value after --name")
            sys.exit(1)

    root = os.path.abspath(root_arg)
    if not os.path.isdir(root):
        print(f"Not a directory: {root}")
        sys.exit(1)

    process_folder(root, dry_run, out_name)
    print("\nDry run complete -- no files written." if dry_run else "\nDone.")


if __name__ == "__main__":
    main()
