#!/usr/bin/env python3
"""
generate_barrels.py
---------------------------------------------------
Auto-generates an index.js barrel file in EVERY folder,
re-exporting the named exports found in each .js file
in that folder (skips node_modules, dist, .git, index.js).

Usage:
    python3 generate_barrels.py ./src
    python3 generate_barrels.py ./src --dry     (preview only, no write)

Detects:
    export const X = ...
    export function X(...)
    export class X ...
    export { A, B as C }
Skips "export default" (no stable name to re-export cleanly).
"""

import os
import re
import sys

IGNORE_DIRS = {"node_modules", "dist", "build", ".git", "coverage"}

EXPORT_PATTERNS = [
    re.compile(r"export\s+const\s+([A-Za-z_$][\w$]*)"),
    re.compile(r"export\s+function\s*\*?\s*([A-Za-z_$][\w$]*)"),
    re.compile(r"export\s+class\s+([A-Za-z_$][\w$]*)"),
    re.compile(r"export\s+let\s+([A-Za-z_$][\w$]*)"),
]

EXPORT_BRACE_PATTERN = re.compile(r"export\s*\{([^}]+)\}")
AS_PATTERN = re.compile(r"^([A-Za-z_$][\w$]*)\s+as\s+([A-Za-z_$][\w$]*)$")
BARE_NAME_PATTERN = re.compile(r"^[A-Za-z_$][\w$]*$")


def get_export_names(content: str) -> list:
    names = set()

    for pattern in EXPORT_PATTERNS:
        for m in pattern.finditer(content):
            names.add(m.group(1))

    for brace_match in EXPORT_BRACE_PATTERN.finditer(content):
        inner = brace_match.group(1)
        for part in inner.split(","):
            piece = part.strip()
            if not piece:
                continue
            as_match = AS_PATTERN.match(piece)
            if as_match:
                names.add(as_match.group(2))
            elif BARE_NAME_PATTERN.match(piece):
                names.add(piece)

    return sorted(names)


def process_folder(dir_path: str, dry_run: bool) -> None:
    try:
        entries = sorted(os.listdir(dir_path))
    except OSError as e:
        print(f"Skipping {dir_path}: {e}")
        return

    lines = []

    for entry in entries:
        full_path = os.path.join(dir_path, entry)

        if os.path.isdir(full_path):
            if entry in IGNORE_DIRS:
                continue
            process_folder(full_path, dry_run)  # recurse first
            continue

        if not entry.endswith(".js"):
            continue
        if entry == "index.js":
            continue

        with open(full_path, "r", encoding="utf-8") as f:
            content = f.read()

        names = get_export_names(content)
        if not names:
            continue

        import_name = "./" + entry
        lines.append(f"export {{ {', '.join(names)} }} from '{import_name}';")

    if not lines:
        return

    lines.sort()
    header = "// AUTO-GENERATED by generate_barrels.py — do not edit by hand\n\n"
    output = header + "\n".join(lines) + "\n"
    index_path = os.path.join(dir_path, "index.js")

    if dry_run:
        print(f"\n--- {index_path} ---")
        print(output)
    else:
        with open(index_path, "w", encoding="utf-8") as f:
            f.write(output)
        print(f"✔ wrote {index_path} ({len(lines)} file(s) re-exported)")


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 generate_barrels.py <rootDir> [--dry]")
        sys.exit(1)

    root_arg = sys.argv[1]
    dry_run = "--dry" in sys.argv

    root = os.path.abspath(root_arg)
    if not os.path.isdir(root):
        print(f"Not a directory: {root}")
        sys.exit(1)

    process_folder(root, dry_run)
    print("\nDry run complete — no files written." if dry_run else "\nDone.")


if __name__ == "__main__":
    main()
